### PR TITLE
Project Setup

### PR DESCRIPTION
**Pull request by Bateyjosue**
# Feature Description 

This is the first project of the Math Magicians application. I set up the environment and tools needed to develop a React application.

- [ ] Make sure that there are no linter errors :white_check_mark: 
- [ ] Make sure that I used the correct Gitflow :white_check_mark: 
- [ ] Make sure that I documented my work in a professional way :white_check_mark: 

## Happy Review

### CODE REVIEW

**Review by BertrandConxy — COMMENTED** [review]
Hi @Bateyjosue , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, **that do not follow Git flow**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bateyjosue** [comment]
Hello @BertrandConxy. thanks for your review. But I'm a bit confused... When you say does not follow git-flow you mean I have to create a `dev` branch and then push changes to it or?

**Comment by BertrandConxy** [comment]
Yeah.. You will need to create dev-branch and then make it the default branch

then after all your pull request will be merging into dev branch instead of main 😀👍

**Comment by Bateyjosue** [comment]
Yeah It done lemme just request for review again thanks @BertrandConxy for the response

**Comment by BertrandConxy** [comment]
You are welcome 👍🙏

**Pull request closed without merging**
